name: ExtDN M2 PHPStan
on: [push, pull_request]

jobs:
  phpstan:
    name: M2 PHPStan
    runs-on: ubuntu-latest
    env:
        PHPSTAN_LEVEL: 2
        COMPOSER_VERSION: 2
    steps:
      - uses: actions/checkout@v2
      - uses: extdn/github-actions-m2/magento-phpstan/8.2@master
        with:
          composer_name: ${{ secrets.COMPOSER_NAME }}
          magento_pre_install_script: .github/workflows/extdn-phpstan-pre-install.sh
